### ISSUE TITLE
Python3 support plans ?

### ISSUE THREAD

**Issue by zerxen** [nuagenetworks/bambou#13]
Python3 support plans ?

bambou and on it dependant vspk are not capable of running on python3 in current state:

**E.G typical type casting issues like:**
  File "C:\Users\havrila\AppData\Local\Programs\Python\Python36\lib\site-packages\bambou\nurest_session.py", line 150, in _in_with_statement
    return opname[ord(frame.f_code.co_code[frame.f_lasti + 3])] is "SETUP_WITH"
TypeError: ord() expected string of length 1, but int found

**Comment by little-dude** [comment]
That's really something we should do yes.
I don't have an eta yet though.
@pdellaert thought?

**Comment by pdellaert** [comment]
Agree on the requirement for this, let us look how we can plan this :)

**Comment by zerxen** [comment]
Great, thanks for consideration. 

And gentlemen while we are at it, how much is vspk and all this github stuff officially supported and kept up to date with Nuage releases? I am actually on commercial evaluation between my company and Nokia pre-sales (can pull you into that on request). But can we make vspk target API for development of our Nuage orchestration, or should we fallback rather on direct REST API.

**Comment by pdellaert** [comment]
@zerxen The Nuage VSPK-Python is officially supported and is used in a lot of platforms and at customers. 

As you might have noticed on the VSPK-Python (and other VSPKs), there are official releases matching our Nuage VSP releases. Our VSPKs are automatically generated every time we release a new version (minor and major) so the VSPKs are always up to date with our API's.

**Comment by zerxen** [comment]
Thanks, appreciate the response.

**Comment by dcotruta** [comment]
Hi there.
I'm a developer currently working on a rather large Nuage rollout. I'd like to volunteer to port this to Python3(.6). Of course, after that, I'd need to port VSPK-Python but I figure if I did this first it might generate some movement on that project.

It nearly the end of 2017. Python 3 has been out for almost 10 years. We can't carry on with 2.x code.

**Comment by little-dude** [comment]
@dcotruta you'd have to start with [bambou](https://github.com/nuagenetworks/bambou) which is the library that does the actual requests. I think porting to python3 should be quite easy as long as we don't support python 2.6 anymore. @pdellaert do we still have to support python 2.6?

I agree that it's urgent to start supporting python 3 at this point...

**Comment by pdellaert** [comment]
Agreed on python 3 support urgency. I didn't know we support python 2.6? I do want python 2.7 compatibility... 

@dcotruta, any help is welcome, but please understand that our own QA organisation will also have to run verifications before any external PR's will be merged/accepted as we need to guarantee compatibility

**Comment by pdellaert** [comment]
Provided 3.0 support since release 3.0 of bambou (and used in VSPK 5.2.2 and above)
